name: ensemble-scheduler
channels:
    - conda-forge
dependencies:
    - python==3.10
    - jupyter
    - notebook
    - numpy==1.25.0
    - pandas==2.0.3
    - scikit-learn==1.3.0
    - openpyxl
    - xlrd
    - tqdm
    - pip
    - pip:
        - livelossplot==0.5.5
